// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: e3ViewYvztDa9TzbxJa8p5
// Component: 91ug9QFmht
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Switch from "../../Switch"; // plasmic-import: EulLIyJN4yh/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_icl_mobile_app.module.css"; // plasmic-import: e3ViewYvztDa9TzbxJa8p5/projectcss
import sty from "./PlasmicToggleShowHide.module.css"; // plasmic-import: 91ug9QFmht/css

export type PlasmicToggleShowHide__VariantMembers = {};
export type PlasmicToggleShowHide__VariantsArgs = {};
type VariantPropType = keyof PlasmicToggleShowHide__VariantsArgs;
export const PlasmicToggleShowHide__VariantProps = new Array<VariantPropType>();

export type PlasmicToggleShowHide__ArgsType = {};
type ArgPropType = keyof PlasmicToggleShowHide__ArgsType;
export const PlasmicToggleShowHide__ArgProps = new Array<ArgPropType>();

export type PlasmicToggleShowHide__OverridesType = {
  root?: p.Flex<"div">;
  toggleShowHide?: p.Flex<typeof Switch>;
};

export interface DefaultToggleShowHideProps {
  className?: string;
}

function PlasmicToggleShowHide__RenderFunc(props: {
  variants: PlasmicToggleShowHide__VariantsArgs;
  args: PlasmicToggleShowHide__ArgsType;
  overrides: PlasmicToggleShowHide__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const [isRootActive, triggerRootActiveProps] = useTrigger("usePressed", {});
  const triggers = {
    active_root: isRootActive
  };

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
      data-plasmic-trigger-props={[triggerRootActiveProps]}
    >
      <Switch
        data-plasmic-name={"toggleShowHide"}
        data-plasmic-override={overrides.toggleShowHide}
        className={classNames("__wab_instance", sty.toggleShowHide)}
        defaultChecked={triggers.active_root ? true : undefined}
        isDisabled={triggers.active_root ? undefined : true}
      >
        {triggers.active_root ? "Hide" : "Show"}
      </Switch>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "toggleShowHide"],
  toggleShowHide: ["toggleShowHide"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  toggleShowHide: typeof Switch;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicToggleShowHide__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicToggleShowHide__VariantsArgs;
    args?: PlasmicToggleShowHide__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicToggleShowHide__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicToggleShowHide__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicToggleShowHide__ArgProps,
          internalVariantPropNames: PlasmicToggleShowHide__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicToggleShowHide__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicToggleShowHide";
  } else {
    func.displayName = `PlasmicToggleShowHide.${nodeName}`;
  }
  return func;
}

export const PlasmicToggleShowHide = Object.assign(
  // Top-level PlasmicToggleShowHide renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    toggleShowHide: makeNodeComponent("toggleShowHide"),

    // Metadata about props expected for PlasmicToggleShowHide
    internalVariantProps: PlasmicToggleShowHide__VariantProps,
    internalArgProps: PlasmicToggleShowHide__ArgProps
  }
);

export default PlasmicToggleShowHide;
/* prettier-ignore-end */
